### ISSUE TITLE
Add fav icon

### ISSUE THREAD

**Issue by kd-singh-dev** [bondmaintainer/bondmaintainer.github.io#2]
![image](https://user-images.githubusercontent.com/50829119/108470108-7011f380-72af-11eb-83e0-9f1793288972.png)

add a favicon for bond maintainer

**Comment by SHUBHANSHU-creator** [comment]
I would like to work on this issue

**Comment by kd-singh-dev** [comment]
@SHUBHANSHU-creator,  go-ahead

**Comment by SHUBHANSHU-creator** [comment]
which pic should I use for favicon.......should I make it myself?

**Comment by kd-singh-dev** [comment]
Yess @SHUBHANSHU-creator, make it yourself .

**Comment by SHUBHANSHU-creator** [comment]
can u explain your project a lil ....what kind of icon would u like
