### ISSUE TITLE
Add animation to the 1st two non animated sections

### ISSUE THREAD

**Issue by kd-singh-dev** [bondmaintainer/bondmaintainer.github.io#3]
![image](https://user-images.githubusercontent.com/50829119/108470216-a0f22880-72af-11eb-8c0c-1d60485cff94.png)
![image](https://user-images.githubusercontent.com/50829119/108470263-b36c6200-72af-11eb-89b6-12948f890da3.png)

### This link may help
 https://michalsnik.github.io/aos/

**Comment by BhawnaAtrish** [comment]
i would like to work on this. Can you assign this to me?

**Comment by kd-singh-dev** [comment]
Sorry, @BhawnaAtrish This issue has already been resolved.

I had my exams so was unable to close this issue, sorry for your inconvenience.

**Comment by BhawnaAtrish** [comment]
oh! its fine.
